config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/GuillermoDiazSM/pyKinectData:
      branch: main
      repo: https://github.com/GuillermoDiazSM/pyKinectData
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/GuillermoDiazSM/pyKinectData git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-cyan-insect.sh
        container: qc.acc_greasy-tangerine-hamster
  QC.Doc:
    repos:
      github.com/GuillermoDiazSM/pyKinectData find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-beige-bongo.sh
        container: qc.doc_grumpy-chartreuse-loon
      github.com/GuillermoDiazSM/pyKinectData git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-sangria-caterpillar.sh
        container: qc.doc_shaky-vermilion-ferret
      github.com/GuillermoDiazSM/pyKinectData markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-mustard-heron.sh
        container: qc.doc_wiggy-seashell-maltese
  QC.Lic:
    repos:
      github.com/GuillermoDiazSM/pyKinectData licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-cerise-moorhen.sh
        container: qc.lic_wiggy-goldenrod-tapir
  QC.Ver:
    repos:
      github.com/GuillermoDiazSM/pyKinectData get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-magnolia-echidna.sh
        container: qc.ver_frumpy-sangria-fly
timeout: 5400
